require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MigrationsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Migration. As you add validations to Migration, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MigrationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all migrations as @migrations" do
      migration = Migration.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:migrations)).to eq([migration])
    end
  end

  describe "GET #show" do
    it "assigns the requested migration as @migration" do
      migration = Migration.create! valid_attributes
      get :show, {:id => migration.to_param}, valid_session
      expect(assigns(:migration)).to eq(migration)
    end
  end

  describe "GET #new" do
    it "assigns a new migration as @migration" do
      get :new, {}, valid_session
      expect(assigns(:migration)).to be_a_new(Migration)
    end
  end

  describe "GET #edit" do
    it "assigns the requested migration as @migration" do
      migration = Migration.create! valid_attributes
      get :edit, {:id => migration.to_param}, valid_session
      expect(assigns(:migration)).to eq(migration)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Migration" do
        expect {
          post :create, {:migration => valid_attributes}, valid_session
        }.to change(Migration, :count).by(1)
      end

      it "assigns a newly created migration as @migration" do
        post :create, {:migration => valid_attributes}, valid_session
        expect(assigns(:migration)).to be_a(Migration)
        expect(assigns(:migration)).to be_persisted
      end

      it "redirects to the created migration" do
        post :create, {:migration => valid_attributes}, valid_session
        expect(response).to redirect_to(Migration.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved migration as @migration" do
        post :create, {:migration => invalid_attributes}, valid_session
        expect(assigns(:migration)).to be_a_new(Migration)
      end

      it "re-renders the 'new' template" do
        post :create, {:migration => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested migration" do
        migration = Migration.create! valid_attributes
        put :update, {:id => migration.to_param, :migration => new_attributes}, valid_session
        migration.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested migration as @migration" do
        migration = Migration.create! valid_attributes
        put :update, {:id => migration.to_param, :migration => valid_attributes}, valid_session
        expect(assigns(:migration)).to eq(migration)
      end

      it "redirects to the migration" do
        migration = Migration.create! valid_attributes
        put :update, {:id => migration.to_param, :migration => valid_attributes}, valid_session
        expect(response).to redirect_to(migration)
      end
    end

    context "with invalid params" do
      it "assigns the migration as @migration" do
        migration = Migration.create! valid_attributes
        put :update, {:id => migration.to_param, :migration => invalid_attributes}, valid_session
        expect(assigns(:migration)).to eq(migration)
      end

      it "re-renders the 'edit' template" do
        migration = Migration.create! valid_attributes
        put :update, {:id => migration.to_param, :migration => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested migration" do
      migration = Migration.create! valid_attributes
      expect {
        delete :destroy, {:id => migration.to_param}, valid_session
      }.to change(Migration, :count).by(-1)
    end

    it "redirects to the migrations list" do
      migration = Migration.create! valid_attributes
      delete :destroy, {:id => migration.to_param}, valid_session
      expect(response).to redirect_to(migrations_url)
    end
  end

end
